FROM eclipse-temurin:17-jdk
ADD ./target/eureka-main.jar app.jar

# 修改容器内的时区
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone

# 各个参数按情况可自行修改
ENTRYPOINT ["java","-jar","/app.jar"]